---
title: "EDA"
editor: visual
---

```{r}
library(tidytuesdayR)
library(tidyverse)
library(arsenal)
library(ggplot2)
library(shiny)
library(dplyr)
library(readr)
library(viridis)

video_games <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2019/2019-07-30/video_games.csv")
```

```{r}
#EDA
head(video_games)



# video_games %>%
#   tableby( ~ ., data = .) %>%
#   summary()

```

> There are 26,688 rows and 10 columns in this data (26,688 observations and 10 variables). I ran tableby() before, but there are too many things so I didn't show the results.

```{r}
#Plots

video_games_deve <- video_games %>%
  group_by(developer) %>%
  summarize(num_games = n(),
            avg_score = mean(metascore, na.rm = TRUE),
            avg_price = mean(price, na.rm = TRUE),
            avg_time = mean(average_playtime, na.rm = TRUE),
            med_time = mean(median_playtime, na.rm = TRUE))%>%
  filter(num_games >= 5,
         !is.nan(avg_score),
         !is.na(developer))

video_games %>%
  separate(release_date, c("month_date", "year"), sep = ", ")%>%
  count(year)


#Price vs. score
video_games_deve %>%
  ggplot(aes(x = avg_score, y = avg_price, color = num_games))+
  geom_point()+
  geom_smooth(se = FALSE, method = "lm",color = "blue")+
  labs(x = "Average Metascore", y = "Average Price", color = "number of games")+
  theme_minimal()

#Price vs. play time
video_games_deve %>%
  ggplot(aes(x = avg_time, y = avg_price, color = num_games))+
  geom_point()+
  geom_smooth(se = FALSE, method = "lm",color = "blue")+
  labs(x = "Average Play Time", y = "Average Price", color = "number of games")+
  theme_minimal()
  

video_games %>% 
  na.omit() %>%
  ggplot(aes(x = price, y = metascore))+
  geom_point()+
  geom_smooth()

video_games %>% 
  filter(average_playtime > 100,
         !is.na(metascore))%>%
  ggplot(aes(x = metascore, y = average_playtime))+
  geom_point()+
  geom_smooth(se = FALSE, method = "lm")


```
